### ISSUE TITLE
Endpoints disappear when k8s cluster is rebooted

### ISSUE THREAD

**Issue by plevart** [olli-ai/glusterfs-subdir-external-provisioner#1]
Hi,

I deployed glusterfs-client-provisioner 1.0.1 via Helm chart. I modified values.yaml and instructed to create an Endpoints object during deployment. The provisioner pod uses this Endpoints to find-out what are the nodes of the GlusterFS cluster. It all worked until I rebooted the k8s cluster at which time, I found that the Endpoints object was not there any more and that the provisioner pod couldn't mount the GlusterFS volume(s)...

I think there should be a Service object with the same name/namespace as Endpoints (a minimal one - a headless service for example) in order to keep the Endpoints object from being removed at reboot time. WDYT?

**Comment by aure-olli** [comment]
Hi. Nice to hear people are using my tools :)
Apparently it's a long known problem I wasn't aware about:
https://github.com/kubernetes/kubernetes/issues/12964
I don't know if it has been fixed in recent kubernetes versions, I haven't encountered the problem yet in my `1.20`, which version are you running ?
I'll check more throughly tomorrow, seems like kubernetes automatically cleans endpointa, the solution is to create a service with the same name, would be a good idea to create the whole mess directly from the helm chart.

**Comment by plevart** [comment]
Hi,
Thank you for creating this provisioner. It's the only non-cloud way to get ReadWriteMany volumes on bare-metal k8s besides NFS. 
I'm running k8s 1.20.5 installed with kubeadm.
Yes, it seems the Endpoints is a derived resource (from Service) and it is removed when endpoint controller is rebooted and there is not corresponding Service resource. I added the following Service to keep the Endpoints around when my cluster reboots:
```
kind: Service
apiVersion: v1
metadata:
  name: glusterfs-client-provisioner
  namespace: glusterfs-client-provisioner
spec:
  ports:
    - name: one
      protocol: TCP
      port: 1
  clusterIP: None
  type: ClusterIP
```
